language: android
sudo: true
android:
  components:
    - build-tools-22.0.1
    - build-tools-23.0.2
    - android-23
    - android-22
    - extra-android-support
    - extra-android-m2repository
  licenses:
    - 'android-sdk-license-.+'
    - '.*intel.+'
script:
